# Generated by Django 3.2.12 on 2022-11-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Catagorys', to='blogapp.catagory'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='blogapp.blog'),
        ),
    ]
